name: ASTLinux

on:
  workflow_dispatch:
    branches: ASTLinux

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: ./Configure
    - name: make
      run: make

