name: ASTLinux

on:
  workflow_dispatch:
    branches: ASTLinux

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup access
      run: chmod -R 777 ./IPCIF
    - name: Configure
      working-directory: ./IPCIF
      run: ./Configure
    - name: make
      working-directory: ./IPCIF
      run: make

