name: AST for Win32

on: [workflow_dispatch, fork, release]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: test_vswhere
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: vswhere

    - name: Build x86
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: $env:PATH="$env:PATH;C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin";msbuild -m -p:Configuration=Release -p:Platform=Win32 .\IPCIF\src\project\win\win32.sln

    - name: Build x64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: $env:PATH="$env:PATH;C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin";msbuild -m -p:Configuration=Release -p:Platform=x64 .\IPCIF\src\project\win\win32.sln

    - name: Setup Install x86
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: cd .\IPCIF\bin;ren Release ASTBin_Win_x86;..\..\misc\tools\zip\zip -r -S ASTBin_Win_x86.zip ASTBin_Win_x86;rd -recurse ASTBin_Win_x86

    - name: Setup Install x64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: cd .\IPCIF\bin\x64;ren Release ASTBin_Win_x64;..\..\..\misc\tools\zip\zip -r -S ASTBin_Win_x64.zip ASTBin_Win_x64;cd ..;move x64\ASTBin_Win_x64.zip .\;rd -recurse x64

    - uses: actions/upload-artifact@v2
      with:
        name: ASTBin.zip
        path: ${{env.GITHUB_WORKSPACE}}IPCIF\bin\
        retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: ASTBin.zip
        path: build/AST_Release

    - name: Create clear file
      run: touch .clear-target-files

    - name: Publish
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:caibinwav123456/Pub.git
        BRANCH: main
        FOLDER: build
        CLEAR_GLOBS_FILE: .clear-target-files
        SSH_PRIVATE_KEY: ${{secrets.DEPLOY_PRIVATE_KEY}}
